### ISSUE TITLE
LVars for FCU values?

### ISSUE THREAD

**Issue by VespaChris** [Fragtality/PilotsDeck_FNX#11]
Hello,

Your solution reading out HDG, SPD, ALT and VS from FCU is great.

Would it be possible to write the values above in LVars as well?

Thanks and best regards,
Christian

**Comment by Fragtality** [comment]
Thanks!
Already done for the next Version 😉 
You can preview it with the latest Version: https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip

**Comment by VespaChris** [comment]
That sounds great, will try it out asap.

Could you please let me now the LVar names?

Thanks,
Christian

**Comment by Fragtality** [comment]
Just configure the raw value mode and the lvar output in the config file. then start the binary and you should see a text file with their names.
I forgot to mention: the WASM Module from MobiFlight is now required for the binary to work!

**Comment by VespaChris** [comment]
Thanks, will do.

**Comment by Fragtality** [comment]
Changes included in Release 0.9
