### ISSUE TITLE
Current aircraft is not the Fenix A320

### ISSUE THREAD

**Issue by Narvik-Ramius** [Fragtality/PilotsDeck_FNX#5]
Hi,

Fist many thanks for this much expected tool :-)

However, I can't make it run properly. I keep getting this error in logfile :
[INF] WaitForFenixAircraft: Current Aircraft is not the Fenix A320 - waiting 30s for Retry

I tried automatic start with FSUIPC, killed the process and restarted it, started it manually from main screen with and without administrative rights, the tool never seems to detect the Fenix is up and running. Any idea please ?

If that might interested you (as soon as I'll be able to read the values ...) I should be able to provide a LUA script that writes the values into custom LVARS (to be able to use them with SPAD.NEXT, AIRMANAGER, or anything else that can read LVARS)

**Comment by Fragtality** [comment]
Hi there!

Seems you are using the latest Version 0.6, right?

> I tried automatic start with FSUIPC, killed the process and restarted it, started it manually from main screen with and without administrative rights, the tool never seems to detect the Fenix is up and running. Any idea please ?

When you say from main screen: Did you try to actually start a flight?


> If that might interested you (as soon as I'll be able to read the values ...) I should be able to provide a LUA script that writes the values into custom LVARS (to be able to use them with SPAD.NEXT, AIRMANAGER, or anything else that can read LVARS)

Thanks, but not really needed for Users of the StreamDeck/PilotsDeck Profiles, since everything is preconfigured for the Offsets.

**Comment by Narvik-Ramius** [comment]
Hi Fragtality, many thanks for your reply. 
After a few times, it finally worked ... Didn't understand why it didn't work previously... But, at least, it seems ok now.
