### ISSUE TITLE
PilotsDeck_FNX StreamDeck profile issues

### ISSUE THREAD

**Issue by MichaelOlsenDK** [Fragtality/PilotsDeck_FNX#6]
I found that the XL profile from the GitHub page does not work - StreamDeck can't understand it. But the StreamDeck XL profile from FlightSim.To works fine.

In the profile MIP page - the baro increase/decrease does not work. The button (+) is set to LuaToggle:FNX320_AUTO:43 (FNX_ISIS_INC in the LUA script). I believe it should be LuaToggle:FNX320_AUTO:13 (FNX_BARO_IN). The same for decrease.

Thanx for a very good work

**Comment by Fragtality** [comment]
> I found that the XL profile from the GitHub page does not work - StreamDeck can't understand it. But the StreamDeck XL profile from FlightSim.To works fine.

Strange, maybe I forgot to update them. Thanks for the Info.

> In the profile MIP page - the baro increase/decrease does not work. The button (+) is set to LuaToggle:FNX320_AUTO:43 (FNX_ISIS_INC in the LUA script). I believe it should be LuaToggle:FNX320_AUTO:13 (FNX_BARO_IN). The same for decrease.

Then your believe is wrong. It is the ISIS. The Barometer is not on the MIP, therefore it is found under EFIS/GLSD :wink:
