### ISSUE TITLE
Current aircraft is not the Fenix A320 // No display returned to my FCU

### ISSUE THREAD

**Issue by Anrolosia** [Fragtality/PilotsDeck_FNX#7]
Hello @Fragtality !

I have the same issue as Delta-Charlie-DEV in issue #5 , I can control my Fenix with my Arduino (SimpleFCU), but somehow, displays are not working, and in the logs, I have "Current Aircraft is not the Fenix A320 - waiting 30s for Retry"

I tried a lot of things, including updating all software to the latest and greatest, but no success so far.

How could I help you to help me?

Thanks a lot!

**Comment by Fragtality** [comment]
- Well, Logs would be good Thing 😉 
- Then: Steam or MS Store Version?
- The full/absolute Path to the aircraft.cfg of the Fenix

**Comment by Anrolosia** [comment]
Hey :) Yes, of course, sorry, you can find the logs attached, let me know if you need more
[FSUIPC7.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10375744/FSUIPC7.log)
[FNX2PLD20230109.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10375746/FNX2PLD20230109.log)
It's the Steam version
The full path is: C:\Users\crash\AppData\Roaming\Microsoft Flight Simulator\Packages\Community\fnx-aircraft-320\SimObjects\Airplanes\FNX320\aircraft.CFG

**Comment by Fragtality** [comment]
Please use this special Build: https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip
(Requires .NET 7: https://dotnet.microsoft.com/en-us/download/dotnet/7.0)

When the Issue happens again, send the Logs from when it happened.
Also: Does this Issue occur regardless if MSFS was started with the Fenix or not? (MSFS has the habbit of partially loading the last used Aircraft when it starts)

**Comment by Anrolosia** [comment]
I appreciate your help! Still same issue, here is the logs:
[FNX2PLD20230109.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10376120/FNX2PLD20230109.log) (the second part after the big ------- line)
[FSUIPC7.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10376122/FSUIPC7.log)

On my side the issue always occurs, no matter if MSFS was started or not with the Fenix

**Comment by Fragtality** [comment]
Redownload the latest Build, it may fix the Issue: https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip

For Reasons unknown, the Case-Invariant String.Contains Function becomes Case-Sensitive when the String contains Spaces ?!? 😮

**Comment by Anrolosia** [comment]
You did it! This build works! I'll let know the SimpleFCU creator, because some others have the same issue has myself.
Thanks a lot for your help!

**Comment by Anrolosia** [comment]
Hummm, it works for a while but diplay crash with an alt at 97296 and a spd at 000 ...
There is the log.
[FNX2PLD20230109.log](https://github.com/Fragtality/PilotsDeck_FNX/files/10376587/FNX2PLD20230109.log)
Any ideas?

**Comment by Fragtality** [comment]
The Log does not show that the Plugin is crashing? I can't do anything about the SimpleFCU HW/SW. The Software I offer does work without a Issue.

Also please remember: the Raw-Values Mode (which is probably/hopefully used by SimpleFCU) is not the Default. Have you (re)enabled it in the Config-File (PilotsDeck_FNX2PLD.dll.config)?

You can also tell the SimpleFCU Creator, that the Binary now does also export the "is Dashed" State of the FCU Displays - so it can be even more accurate now! 😃 
Hope it works for all, does work for me across multiple MSFS/Windows Sessions.

**Comment by Anrolosia** [comment]
I did a test flight and everything was working as expected! But, as a side note, with raw-values to false.

I sent a message to the SimpleFCU creator to check this issue for the "is Dashed".

Thanks a lot for your great work!

**Comment by Delta-Charlie-DEV** [comment]
Hi @Fragtality  - sorry for "reopening" but the previous download link you gave (https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip) doesn't seem to work any more (404)

**Comment by Fragtality** [comment]
> I did a test flight and everything was working as expected! But, as a side note, with raw-values to false.
I sent a message to the SimpleFCU creator to check this issue for the "is Dashed".

He should check out the Raw-Value Mode - it was specifically designed for such 3rd Party Applications which drive their own Displays.

@Delta-Charlie-DEV 
I've had released Version 0.7 and deleted the latest File therefor. Only to realize a little later that the Batteries need Attention again (this damn Batteries!^^) and because of that had to withdraw the 0.7 Release -.-
I uploaded the latest Build again: https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip

**Comment by Delta-Charlie-DEV** [comment]
Great - thanks 👍 
By any chance (sorry it's probably not the best place to ask, but I won't open an issue for that), do you plan to fetch additionnal  information in a later build ? for example the overhead ADIRS quartz screen  :-)

**Comment by Fragtality** [comment]
Not really to be honest.
I'm happy that the Binary also helps with other Tools/3rd Party HW, but it was never intended for serious Cockpit-Building (which does not make Sense imho with the Fenix). For that Reason it provides only the "essential" Stuff to allow Flights with near to zero Mouse-Interactions needed. The ADIRS Screen is not really that Essential (not even Common in every A320). On top of that, it is even harder to find (I did indeed tried to). I would need to find the raw Values for every mode and then would need to build a String out of it - I don't directly get the Display Content as finished String!

The only thing I thought about is maybe adding the Com2 Displays, if Users want to build a FO-Setup. BUT: the current Com1 Displays work exactly like in the Cockpit, so if you select VHF2/3 on RMP1 you see the Frequencies there. So Com2 is also not really needed, if flying in the Captain Seat.
