### ISSUE TITLE
Read EFIS Baro - SteamDeck+

### ISSUE THREAD

**Issue by AFN40** [Fragtality/PilotsDeck_FNX#9]
First of all, thank you so much for this fantastic program! Really am loving it. I'm 99% there. Only thing I can't quite figure out is how to get the stream deck to read the current EFIS baro level. When I loaded the Stream Deck+ profile, it came preconfigured to read/adjust the ISIS baro. Any way to get it so it's reading/adjusting the EFIS baro? I tried with the screenshot below. The +/- works, push in for standby works. But nothing I've tried will read the baro setting. 

Thanks again! 

![Screenshot 2023-01-26 205316](https://user-images.githubusercontent.com/36092631/214993554-a2db7c71-cb89-491d-af4a-0d7819226758.png)

**Comment by Fragtality** [comment]
Scripts correctly configured / started? (FNX320_SYNC generates the EFSI Baro Display )
MSFS started with Fenix, respectively no other Plane was loaded? (FSUIPC can't handle large amounts of Lvars, and when there are too much, the Plugin or other Clients can't access the Lvars anymore)
And I don't think you want to use the Reset Switch Option ...

**Comment by AFN40** [comment]
Thanks for the reply. I believe they are started correctly. The AP FCU displays work perfectly on page 3 of the profile I imported. (Speed, Heading & Altitude) Would that mean the scripts are working as intended? 
Tried launching the sim multiple times, all directly to fenix. 
And good catch. Unchecked that box. 

Was i correct in grabbing the read value address from here: 

function FNX_SYNC()
	ticks = ticks + 1
	FNX_READ_LANDING_LGT() --0x5400 + 1
	**FNX_READ_BARO()	--0x5401 + 5**
	FNX_READ_GEAR() --0x5406/0x5407 + 1
	--0x5408 --> 0x5xxx used in Binary
	FNX_READ_CLOCK() --0x5500 + 9
	FNX_READ_TRIM() --0x5509 + 8

**Comment by Fragtality** [comment]
The FCU Display-Contents are not generated by the Script. They are generated by this Tool here and both have no dependency on each other  😉 

So you believe the Script is running? How do you have it configured in the FSUIPC7.ini? (If you think "huh?!" now - please read the the [Readme](https://github.com/Fragtality/PilotsDeck/tree/master/Integrations/Fenix%20A320#requirements--installation))

**Comment by AFN40** [comment]
The one configured in the profile was reading/adjusting the ISIS baro. Not the EFIS. Maybe that's fine? 

Here is what I have amended to the FSUIPC7.ini file. 

[Programs]
RunIf1=READY,KILL,C:\PilotsDeck_FNX2PLD\PilotsDeck_FNX2PLD.exe

[LuaFiles]
1=FNX320_AUTO
2=FNX320_SYNC
3=GSX_AUTO
4=GSX_AUTO_FNX
5=PilotsDeck
6=747_8
7=DSA_GSX_AUTO
8=PilotsDeck_737

[Auto]
1=Lua GSX_AUTO

[Auto.FNX320]
1=Lua FNX320_AUTO
2=Lua FNX320_SYNC

[Auto]
1=Lua GSX_AUTO
2=Lua FNX320_AUTO
3=Lua FNX320_SYNC

**Comment by AFN40** [comment]
And yes plane is powered ;-)

**Comment by Fragtality** [comment]
> The one configured in the profile was reading/adjusting the ISIS baro. Not the EFIS. Maybe that's fine?

No, it contains both the EFIS and ISIS on that page.


Uhm - a Section in the Ini should only exist once. The Scripts should be either Global or Profile-Specific but not both.
So it is either this (IF your FSUIPC Profile is also named FNX320!!!):
```
[Auto.FNX320]
1=Lua FNX320_AUTO
2=Lua FNX320_SYNC

[Auto]
1=Lua GSX_AUTO
```

or this (in case your answer to your FSUIPC7 Profile's Name for the Fenix is "huh!?"):
```
[Auto]
1=Lua GSX_AUTO
2=Lua FNX320_AUTO
3=Lua FNX320_SYNC
```

Only regarding the Auto-Sections! Programs and LuaFiles is fine.

**Comment by Fragtality** [comment]
And something else on the Plugin:
You don't have to use the Limits for the Lvar Manipulation (e.g. `$+1:500`) if there is none or you do not care about it! Just `$+1` would also be ok.
And like described in Issue 15 of the Plugin: Manipulating the Lvar via Calculator-Code is often "more fluid" for the Encoders than via Lvar Action-Type. You don't need to know RPN for that, just write `$E_FCU_EFIS1_BARO:-1` as the Address for the Calculator Action-Type (for decrease)

**Comment by AFN40** [comment]
Oh wow, i can't believe i didn't notice that. Removing the duplicate section in the .ini file worked! Seriously thank you for such a wonderful plugin. If there is a way i can contribute, please let me know. Cheers!

**Comment by Fragtality** [comment]
Just spread the Word, that there is an Alternative to the other and paid StreamDeck-Plugins for Simming. It surely is not for everyone, but for a considerable amount of People it seems to be the better Option 😉

**Comment by AFN40** [comment]
You got it!
